<a href="https://colab.research.google.com/github/ersjunior/3DTS-FeatureEngineering/blob/main/A1_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 1 - Feature Engineering

* Hands ON

In [1]:
import numpy as np
from sklearn.impute import KNNImputer

In [2]:
X = [[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]]
X

[[1, 2, nan], [3, 4, 3], [nan, 6, 5], [8, 8, 7]]

In [3]:
imputer = KNNImputer(n_neighbors=2)
imputer.fit_transform(X)

array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])

In [4]:
# knn imputation transform for the horse colic dataset
from numpy import isnan
from pandas import read_csv

# Carrega  dataset
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/horse-colic.csv'
dataframe = read_csv(url, header=None, na_values='?')

dataframe

0   1        2     3      4     5    6    7    8    9   ...    18    19  \
0    2.0   1   530101  38.5   66.0  28.0  3.0  3.0  NaN  2.0  ...  45.0   8.4   
1    1.0   1   534817  39.2   88.0  20.0  NaN  NaN  4.0  1.0  ...  50.0  85.0   
2    2.0   1   530334  38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...  33.0   6.7   
3    1.0   9  5290409  39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...  48.0   7.2   
4    2.0   1   530255  37.3  104.0  35.0  NaN  NaN  6.0  2.0  ...  74.0   7.4   
..   ...  ..      ...   ...    ...   ...  ...  ...  ...  ...  ...   ...   ...   
295  1.0   1   533886   NaN  120.0  70.0  4.0  NaN  4.0  2.0  ...  55.0  65.0   
296  2.0   1   527702  37.2   72.0  24.0  3.0  2.0  4.0  2.0  ...  44.0   NaN   
297  1.0   1   529386  37.5   72.0  30.0  4.0  3.0  4.0  1.0  ...  60.0   6.8   
298  1.0   1   530612  36.5  100.0  24.0  3.0  3.0  3.0  1.0  ...  50.0   6.0   
299  1.0   1   534618  37.2   40.0  20.0  NaN  NaN  NaN  NaN  ...  36.0  62.0   

      20   21   22  23     24  25  26  27  
0    NaN  NaN  2.0   2  11300   0   0   2  
1    2.0  2.0  3.0   2   2208   0   0   2  
2    NaN  NaN  1.0   2      0   0   0   1  
3    3.0  5.3  2.0   1   2208   0   0   1  
4    NaN  NaN  2.0   2   4300   0   0   2  
..   ...  ...  ...  ..    ...  ..  ..  ..  
295  NaN  NaN  3.0   2   3205   0   0   2  
296  3.0  3.3  3.0   1   2208   0   0   1  
297  NaN  NaN  2.0   1   3205   0   0   2  
298  3.0  3.4  1.0   1   2208   0   0   1  
299  1.0  1.0  3.0   2   6112   0   0   2  

[300 rows x 28 columns]

In [5]:
# Divide as Features e o Rótulo
data = dataframe.values
ix = [i for i in range(data.shape[1]) if i != 23]
X, y = data[:, ix], data[:, 23]
X, y

(array([[2.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
         0.00000e+00, 2.00000e+00],
        [1.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
         0.00000e+00, 2.00000e+00],
        [2.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
         0.00000e+00, 1.00000e+00],
        ...,
        [1.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0.00000e+00,
         0.00000e+00, 2.00000e+00],
        [1.00000e+00, 1.00000e+00, 5.30612e+05, ..., 0.00000e+00,
         0.00000e+00, 1.00000e+00],
        [1.00000e+00, 1.00000e+00, 5.34618e+05, ..., 0.00000e+00,
         0.00000e+00, 2.00000e+00]]),
 array([2., 2., 2., 1., 2., 2., 1., 1., 1., 2., 1., 1., 2., 2., 1., 1., 2.,
        2., 1., 2., 1., 2., 1., 1., 1., 2., 1., 2., 2., 2., 1., 1., 1., 1.,
        1., 1., 2., 1., 2., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1., 2., 2.,
        1., 2., 2., 1., 1., 1., 1., 1., 1., 2., 2., 1., 2., 1., 1., 1., 2.,
        2., 2., 1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1

In [6]:
#Total missing
print('Missing: %d' % sum(isnan(X).flatten()))

Missing: 1605


In [7]:
# Define o imputer
imputer = KNNImputer()
# Calibra o Imputer sobre o dataset
imputer.fit(X)


# Tranforma o Dataset
Xtrans = imputer.transform(X)
#Total missing
print('Missing: %d' % sum(isnan(Xtrans).flatten()))

Missing: 0
